version: "3.9"

networks:
  litellm:

services:
  litellm:
    #image: ghcr.io/berriai/litellm:main-v1.23.15
    image: ghcr.io/berriai/litellm-database:main-v1.23.15
    env_file:
      - /home/bdr/.source/mistral.env
    networks:
      - litellm
    volumes:
      - ./config/litellm/config.yaml:/app/config.yaml
    command:
      [
        "--config",
        "/app/config.yaml",
        "--port",
        "8000",
        "--num_workers",
        "8"
      ]
    depends_on:
      #- ollama
      - redis
    ports:
      - 8000:8000
    #environment:
    #  REDIS_HOST: redis
    #  REDIS_PORT: 6379
    #  REDIS_PASSWORD: SDsdgFsfm4lmf43lfnm34lkf

  redis:
    image: redis:7-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    environment:
      REDIS_PASSWORD: SDsdgFsfm4lmf43lfnm34lkf
    volumes:
      - ./data/redis:/data
    networks:
      - litellm
  #postgres:
  #  image: postgres:alpine
  #  shm_size: 128mb
  #  environment:
  #    POSTGRES_PASSWORD: w9s3j9s3js92ß9sjß9
  #    PGDATA: /var/lib/postgresql/data/pgdata
  #  volumes:
  #    - ./data:/var/lib/postgresql/data
